# -*- coding: utf-8 -*-
"""scraper_2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NX-4HEmRgzB9_3JteoVNTje3laqdgAFF
"""

#imports
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
import time

all_matches = []
main_url= "https://fbref.com/en/comps/106/Womens-World-Cup-Stats"

data = requests.get(main_url) #html scraped
soup = BeautifulSoup(data.text) #parsing
standings_table = soup.select('table.stats_table')[8] #css selector of the main table

links = [l.get("href") for l in standings_table.find_all('a')] # get the links in the table
links = [l for l in links if '/squads/' in l]
team_urls = [f"https://fbref.com{l}" for l in links]
team_urls

for team_url in team_urls: # to get each team in the main table
    time.sleep(10)
    team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
    data = requests.get(team_url)
    html= StringIO(data.text)
    try:
        matches = pd.read_html(html, match="Scores & Fixtures")[0]
    except ValueError:
        continue
    time.sleep(3)
    soup = BeautifulSoup(data.text)
    links = [l.get("href") for l in soup.find_all('a')]
    links = [l for l in links if l and '/shooting/' in l]
    data = requests.get(f"https://fbref.com{links[0]}")
    html= StringIO(data.text)
    time.sleep(3)
    try:
        shooting = pd.read_html(html, match="Shooting")[0]
    except ValueError:
        continue
    shooting.columns = shooting.columns.droplevel()
    time.sleep(3)
    try:
        team_data = matches.merge(shooting[["Date", "Sh", "SoT", "SoT%", "G/Sh", "G/SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
    except ValueError:
        continue
    team_data = team_data[team_data["Comp"] == "World Cup"]

    team_data["Season"] = 2023
    team_data["Team"] = team_name
    all_matches.append(team_data)
    time.sleep(3)

matches_2023 = pd.concat(all_matches)

matches_2023.to_csv("WWC_2023_matches.csv")

matches_2023 = pd.read_csv("WWC_2023_matches.csv")
matches_2023

matches_2023 = matches_2023.drop(columns=['Unnamed: 0'])
matches_2023